Dict = {"hiragana": [
  {"type":"vowel",
  "table":[
    {"uniqueID":"h1","character":"あ","romaji":"a","referenceWords":["ahri", "anata", "ao"],"refImage":""},
    {"uniqueID":"h2","character":"い","romaji":"i","referenceWords":[""],"refImage":""},
    {"uniqueID":"h3","character":"う","romaji":"u","referenceWords":[""],"refImage":""},
    {"uniqueID":"h4","character":"え","romaji":"e","referenceWords":[""],"refImage":""},
    {"uniqueID":"h5","character":"お","romaji":"o","referenceWords":[""],"refImage":""},]}
  ,
  {"type":"k",
  "table":[
    {"uniqueID":"h6","character":"か","romaji":"ka","referenceWords":[""],"refImage":""},
    {"uniqueID":"h7","character":"き","romaji":"ki","referenceWords":[""],"refImage":""},
    {"uniqueID":"h8","character":"く","romaji":"ku","referenceWords":[""],"refImage":""},
    {"uniqueID":"h9","character":"け","romaji":"ke","referenceWords":[""],"refImage":""},
    {"uniqueID":"h10","character":"こ","romaji":"ko","referenceWords":[""],"refImage":""},]}
  ,  
  {"type":"s",
  "table":[
    {"uniqueID":"h11","character":"さ","romaji":"sa","referenceWords":[""],"refImage":""},
    {"uniqueID":"h12","character":"し","romaji":"shi","referenceWords":[""],"refImage":""},
    {"uniqueID":"h13","character":"す","romaji":"su","referenceWords":[""],"refImage":""},
    {"uniqueID":"h14","character":"せ","romaji":"se","referenceWords":[""],"refImage":""},
    {"uniqueID":"h15","character":"そ","romaji":"so","referenceWords":[""],"refImage":""},]}
  ,
  {"type":"t",
  "table":[
    {"uniqueID":"h16","character":"た","romaji":"ta","referenceWords":[""],"refImage":""},
    {"uniqueID":"h17","character":"ち","romaji":"chi","referenceWords":[""],"refImage":""},
    {"uniqueID":"h18","character":"つ","romaji":"tsu","referenceWords":[""],"refImage":""},
    {"uniqueID":"h19","character":"て","romaji":"te","referenceWords":[""],"refImage":""},
    {"uniqueID":"h20","character":"と","romaji":"to","referenceWords":[""],"refImage":""},]}
  ,
  {"type":"n",
  "table":[
    {"uniqueID":"h21","character":"な","romaji":"na","referenceWords":[""],"refImage":""},
    {"uniqueID":"h22","character":"に","romaji":"ni","referenceWords":[""],"refImage":""},
    {"uniqueID":"h23","character":"ぬ","romaji":"nu","referenceWords":[""],"refImage":""},
    {"uniqueID":"h24","character":"ね","romaji":"ne","referenceWords":[""],"refImage":""},
    {"uniqueID":"h25","character":"の","romaji":"no","referenceWords":[""],"refImage":""},]}
  , 
  {"type":"h",
  "table":[
    {"uniqueID":"h26","character":"は","romaji":"ha","referenceWords":[""],"refImage":""},
    {"uniqueID":"h27","character":"ひ","romaji":"h","referenceWords":[""],"refImage":""},
    {"uniqueID":"h28","character":"ふ","romaji":"fu","referenceWords":[""],"refImage":""},
    {"uniqueID":"h29","character":"へ","romaji":"he","referenceWords":[""],"refImage":""},
    {"uniqueID":"h30","character":"ほ","romaji":"ho","referenceWords":[""],"refImage":""},]}     
  ,
  {"type":"m",
  "table":[
    {"uniqueID":"h31","character":"ま","romaji":"ma","referenceWords":[""],"refImage":""},
    {"uniqueID":"h32","character":"み","romaji":"mi","referenceWords":[""],"refImage":""},
    {"uniqueID":"h33","character":"む","romaji":"mu","referenceWords":[""],"refImage":""},
    {"uniqueID":"h34","character":"め","romaji":"me","referenceWords":[""],"refImage":""},
    {"uniqueID":"h35","character":"も","romaji":"mo","referenceWords":[""],"refImage":""},]}
  ,
  {"type":"y",
  "table":[
    {"uniqueID":"h36","character":"や","romaji":"ya","referenceWords":[""],"refImage":""},
    {"uniqueID":"h37","character":"ゆ","romaji":"yu","referenceWords":[""],"refImage":""},
    {"uniqueID":"h38","character":"よ","romaji":"yo","referenceWords":[""],"refImage":""},]}
  ,
  {"type":"r",
  "table":[
    {"uniqueID":"h39","character":"ら","romaji":"ra","referenceWords":[""],"refImage":""},
    {"uniqueID":"h40","character":"り","romaji":"ri","referenceWords":[""],"refImage":""},
    {"uniqueID":"h41","character":"る","romaji":"ru","referenceWords":[""],"refImage":""},
    {"uniqueID":"h42","character":"れ","romaji":"ri","referenceWords":[""],"refImage":""},
    {"uniqueID":"h43","character":"ろ","romaji":"ru","referenceWords":[""],"refImage":""},]} 
  ,
  {"type":"w",
  "table":[
    {"uniqueID":"h44","character":"わ","romaji":"wa","referenceWords":[""],"refImage":""},
    {"uniqueID":"h45","character":"を","romaji":"O","referenceWords":[""],"refImage":""}, ]}
  ,
  {"type":"N",
  "table":[
    {"uniqueID":"h46","character":"ん","romaji":"N","referenceWords":[""],"refImage":""},]}
  ]}