Dict = {"katakana": [
  {"type":"vowel",
  "table":[
    {"uniqueID":"k1","character":"ア","romaji":"a","referenceWords":["ahri", "anata", "ao"],"refImage":""},
    {"uniqueID":"k2","character":"イ","romaji":"i","referenceWords":[""],"refImage":""},
    {"uniqueID":"k3","character":"ウ","romaji":"u","referenceWords":[""],"refImage":""},
    {"uniqueID":"k4","character":"エ","romaji":"e","referenceWords":[""],"refImage":""},
    {"uniqueID":"k5","character":"オ","romaji":"o","referenceWords":[""],"refImage":""},]}
  ,
  {"type":"k",
  "table":[
    {"uniqueID":"k6","character":"カ","romaji":"ka","referenceWords":[""],"refImage":""},
    {"uniqueID":"k7","character":"キ","romaji":"ki","referenceWords":[""],"refImage":""},
    {"uniqueID":"k8","character":"ク","romaji":"ku","referenceWords":[""],"refImage":""},
    {"uniqueID":"k9","character":"ケ","romaji":"ke","referenceWords":[""],"refImage":""},
    {"uniqueID":"k10","character":"コ","romaji":"ko","referenceWords":[""],"refImage":""},]}
  ,  
  {"type":"s",
  "table":[
    {"uniqueID":"k11","character":"サ","romaji":"sa","referenceWords":[""],"refImage":""},
    {"uniqueID":"k12","character":"シ","romaji":"shi","referenceWords":[""],"refImage":""},
    {"uniqueID":"k13","character":"ス","romaji":"su","referenceWords":[""],"refImage":""},
    {"uniqueID":"k14","character":"セ","romaji":"se","referenceWords":[""],"refImage":""},
    {"uniqueID":"k15","character":"ソ","romaji":"so","referenceWords":[""],"refImage":""},]}
  ,
  {"type":"t",
  "table":[
    {"uniqueID":"k16","character":"タ","romaji":"ta","referenceWords":[""],"refImage":""},
    {"uniqueID":"k17","character":"チ","romaji":"chi","referenceWords":[""],"refImage":""},
    {"uniqueID":"k18","character":"ツ","romaji":"tsu","referenceWords":[""],"refImage":""},
    {"uniqueID":"k19","character":"テ","romaji":"te","referenceWords":[""],"refImage":""},
    {"uniqueID":"k20","character":"ト","romaji":"to","referenceWords":[""],"refImage":""},]}
  ,
  {"type":"n",
  "table":[
    {"uniqueID":"k21","character":"ナ","romaji":"na","referenceWords":[""],"refImage":""},
    {"uniqueID":"k22","character":"ニ","romaji":"ni","referenceWords":[""],"refImage":""},
    {"uniqueID":"k23","character":"ヌ","romaji":"nu","referenceWords":[""],"refImage":""},
    {"uniqueID":"k24","character":"ネ","romaji":"ne","referenceWords":[""],"refImage":""},
    {"uniqueID":"k25","character":"ノ","romaji":"no","referenceWords":[""],"refImage":""},]}
  , 
  {"type":"h",
  "table":[
    {"uniqueID":"k26","character":"ハ","romaji":"ha","referenceWords":[""],"refImage":""},
    {"uniqueID":"k27","character":"ヒ","romaji":"h","referenceWords":[""],"refImage":""},
    {"uniqueID":"k28","character":"フ","romaji":"fu","referenceWords":[""],"refImage":""},
    {"uniqueID":"k29","character":"ヘ","romaji":"he","referenceWords":[""],"refImage":""},
    {"uniqueID":"k30","character":"ホ","romaji":"ho","referenceWords":[""],"refImage":""},]}     
  ,
  {"type":"m",
  "table":[
    {"uniqueID":"k31","character":"マ","romaji":"ma","referenceWords":[""],"refImage":""},
    {"uniqueID":"k32","character":"ミ","romaji":"mi","referenceWords":[""],"refImage":""},
    {"uniqueID":"k33","character":"ム","romaji":"mu","referenceWords":[""],"refImage":""},
    {"uniqueID":"k34","character":"メ","romaji":"me","referenceWords":[""],"refImage":""},
    {"uniqueID":"k35","character":"モ","romaji":"mo","referenceWords":[""],"refImage":""},]}
  ,
  {"type":"y",
  "table":[
    {"uniqueID":"k36","character":"ヤ","romaji":"ya","referenceWords":[""],"refImage":""},
    {"uniqueID":"k37","character":"ユ","romaji":"yi","referenceWords":[""],"refImage":""},
    {"uniqueID":"k38","character":"ヨ","romaji":"yu","referenceWords":[""],"refImage":""},]}
  ,
  {"type":"r",
  "table":[
    {"uniqueID":"k39","character":"ラ","romaji":"ra","referenceWords":[""],"refImage":""},
    {"uniqueID":"k40","character":"リ","romaji":"ri","referenceWords":[""],"refImage":""},
    {"uniqueID":"k41","character":"ル","romaji":"ru","referenceWords":[""],"refImage":""},
    {"uniqueID":"k42","character":"レ","romaji":"ri","referenceWords":[""],"refImage":""},
    {"uniqueID":"k43","character":"ロ","romaji":"ru","referenceWords":[""],"refImage":""},]} 
  ,
  {"type":"w",
  "table":[
    {"uniqueID":"k44","character":"ワ","romaji":"wa","referenceWords":[""],"refImage":""},
    {"uniqueID":"k45","character":"ヲ","romaji":"O","referenceWords":[""],"refImage":""}, ]}
  ,
  {"type":"N",
  "table":[
    {"uniqueID":"k46","character":"ン","romaji":"N","referenceWords":[""],"refImage":""},]}
  ]}